name: "balancify"
port: 8080
algo: "CH"
type: "W"
maxPoolSize: 256
scalingFactor: 3.2
route:
  - id: "bal-route-1"
    path: "/get_names"
    servers:
      - id: "server-1"
        url: "http://localhost:3000"
        health:
          path: "/health-check"
        size:
          cpu: 2
          memory: 2
      - id: "server-2"
        url: "http://localhost:3002"
        health:
          path: "/health-check"
        size:
          cpu: 5
          memory: 5
healthCheck:
  intervals: 60
