app:
  name: "balancify"
  port: 8080
  algo: "RR"
  route:
    - id: "bal-route-1"
      path: "/api/v1/user/get"
      servers:
        - id: "server-1"
          hostname: "http://localhost:3001"
          health:
            path: "/hc"
          size:
            cpu: 2
            memory: 2
        - id: "server-2"
          hostname: "http://localhost:3002"
          health:
            path: "/hc"
          size:
            cpu: 3
            memory: 3
    - id: "bal-route-2"
      path: "/api/v1/post/get"
      servers:
        - id: "server-1"
          hostname: "http://localhost:3001"
          health:
            path: "/hc"
          size:
            cpu: 4
            memory: 4
        - id: "server-2"
          hostname: "http://localhost:3002"
          health:
            path: "/hc"
          size:
            cpu: 3
            memory: 3

  helathCheck:
    intervals: 5
